import 'dart:io';
import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import '../../../../core/entities/imu_entities.dart';

abstract class ExcelDataSource {
  Future<String> exportResults(List<QaResult> results);
}

class ExcelDataSourceImpl implements ExcelDataSource {
  @override
  Future<String> exportResults(List<QaResult> results) async {
    final desktop = '${Platform.environment['USERPROFILE']}\\Desktop';
    final folder = Directory('$desktop\\GMSyncTestResult');

    if (!await folder.exists()) {
      await folder.create(recursive: true);
    }

    final filePath = '${folder.path}\\test_results.xlsx';
    final file = File(filePath);

    Excel excel;
    if (await file.exists()) {
      final bytes = await file.readAsBytes();
      excel = Excel.decodeBytes(bytes);
    } else {
      excel = Excel.createExcel();
      _createHeaders(excel);
      _addSignature(excel);
    }

    _appendResults(excel, results);

    final bytes = excel.encode();
    if (bytes != null) {
      await file.writeAsBytes(bytes);
    }

    return filePath;
  }

  void _createHeaders(Excel excel) {
    final sheet = excel['Results'];

    sheet.cell(CellIndex.indexByString('A1')).value = TextCellValue('Test Date');
    sheet.cell(CellIndex.indexByString('B1')).value = TextCellValue('Device ID');
    sheet.cell(CellIndex.indexByString('C1')).value = TextCellValue('Status');
    sheet.cell(CellIndex.indexByString('D1')).value = TextCellValue('Failure Reason');
    sheet.cell(CellIndex.indexByString('E1')).value = TextCellValue('Saturation Count');
    sheet.cell(CellIndex.indexByString('F1')).value = TextCellValue('Spike Count');
    sheet.cell(CellIndex.indexByString('G1')).value = TextCellValue('Max Raw');
    sheet.cell(CellIndex.indexByString('H1')).value = TextCellValue('Max Delta');

    for (int i = 0; i < 8; i++) {
      final cell = sheet.cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0));
      cell.cellStyle = CellStyle(
        bold: true,
        backgroundColorHex: ExcelColor.blue,
        fontColorHex: ExcelColor.white,
      );
    }
  }

  void _addSignature(Excel excel) {
    final sheet = excel['Metadata'];
    sheet.cell(CellIndex.indexByString('A1')).value =  TextCellValue('Generated by');
    sheet.cell(CellIndex.indexByString('B1')).value =  TextCellValue('GMSync IMU QA Tester v1.0');
    sheet.cell(CellIndex.indexByString('A2')).value =  TextCellValue('Signature');
    sheet.cell(CellIndex.indexByString('B2')).value =  TextCellValue('AUTHENTICATED_QA_DATA_2025');
    // sheet.setColWidth(0, 20);
    // sheet.setColWidth(1, 40);
    sheet.setColumnWidth(0,20 );
    sheet.setColumnWidth(1, 40);


    // Protect metadata sheet
    sheet.isRTL = false;
  }

  void _appendResults(Excel excel, List<QaResult> results) {
    final sheet = excel['Results'];
    final timestamp = DateTime.now().toString().split('.')[0];

    int nextRow = sheet.maxRows;

    for (final result in results) {
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: nextRow))
          .value = TextCellValue(timestamp);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: nextRow))
          .value = TextCellValue(result.deviceId);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: nextRow))
          .value = TextCellValue(result.passed ? 'PASS' : 'FAIL');
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 3, rowIndex: nextRow))
          .value = TextCellValue(result.failureReason.label);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 4, rowIndex: nextRow))
          .value = IntCellValue(result.saturationCount);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 5, rowIndex: nextRow))
          .value = IntCellValue(result.spikeCount);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 6, rowIndex: nextRow))
          .value = IntCellValue(result.maxAbsRaw);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 7, rowIndex: nextRow))
          .value = IntCellValue(result.maxDelta);

      final statusCell = sheet.cell(CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: nextRow));
      statusCell.cellStyle = CellStyle(
        backgroundColorHex: result.passed ? ExcelColor.green : ExcelColor.red,
      );

      nextRow++;
    }
  }

  ExcelColor _getStatusColor(QaStatus status) {
    switch (status) {
      case QaStatus.pass:
        return ExcelColor.green;
      case QaStatus.warn:
        return ExcelColor.yellow;
      case QaStatus.fail:
        return ExcelColor.red;
    }
  }
}